title: Haoyu Zhang's Homepage
page-top-title: Haoyu Zhang
top-section-bg-text: Power Electronics 
home-subtitle: Haoyu Zhang&ensp;|&ensp;张昊宇
copyright-text: '&copy; Haoyu Zhang 2025. All Rights Reserved.'
